import { Theme, ThemeKey } from "./types";

export const THEMES: Record<ThemeKey, Theme> = {
  blue: {
    name: "Royal Blue",
    primary: "bg-blue-600",
    hover: "hover:bg-blue-500",
    text: "text-blue-400",
    border: "border-blue-500",
    ring: "focus:border-blue-500",
    accentBg: "bg-blue-900/20",
    gradient: "from-blue-600 to-indigo-600",
    hex: "#2563eb",
  },
  cyan: {
    name: "Cyber Cyan",
    primary: "bg-cyan-600",
    hover: "hover:bg-cyan-500",
    text: "text-cyan-400",
    border: "border-cyan-500",
    ring: "focus:border-cyan-500",
    accentBg: "bg-cyan-900/20",
    gradient: "from-cyan-600 to-blue-600",
    hex: "#0891b2",
  },
  orange: {
    name: "Stadia Orange",
    primary: "bg-orange-600",
    hover: "hover:bg-orange-500",
    text: "text-orange-400",
    border: "border-orange-500",
    ring: "focus:border-orange-500",
    accentBg: "bg-orange-900/20",
    gradient: "from-orange-600 to-red-600",
    hex: "#ea580c",
  },
  purple: {
    name: "Neon Purple",
    primary: "bg-purple-600",
    hover: "hover:bg-purple-500",
    text: "text-purple-400",
    border: "border-purple-500",
    ring: "focus:border-purple-500",
    accentBg: "bg-purple-900/20",
    gradient: "from-purple-600 to-pink-600",
    hex: "#9333ea",
  },
  green: {
    name: "Razer Green",
    primary: "bg-green-500",
    hover: "hover:bg-green-400",
    text: "text-green-400",
    border: "border-green-500",
    ring: "focus:border-green-500",
    accentBg: "bg-green-900/20",
    gradient: "from-green-600 to-emerald-700",
    hex: "#44D62C",
  },
};
